### ISSUE TITLE
Bug: crashing with ExtraPropertiesError

### ISSUE THREAD

**Issue by mavam** [MISP/misp-stix#17]
### MISP-STIX usage

Parsing attributes and events from the 0mq feed.

### Expected behavior

I can invoke `MISPtoSTIX21Parser.parse_misp_event` without crashing

### Actual behavior

I'm getting an exception:

```
stix2.exceptions.ExtraPropertiesError: Unexpected properties for Identity: (interoperability).
```

### Steps to reproduce

See the example JSON of the MISP Event that travels via 0mq at the beginning. All I'm doing is invoking `parse_misp_event`.

This is the JSON going into `parse_misp_event` that caused the crash:
```json
{'id': '1', 'orgc_id': '1', 'org_id': '1', 'date': '2022-07-06', 'threat_level_id': '1', 'info': 'Test', 'published': False, 'uuid': '7303f304-e8f1-4318-94f3-4df43a77f0b3', 'attribute_count': '1', 'analysis': '0', 'timestamp': '1657180174', 'distribution': '1', 'proposal_email_lock': False, 'locked': False, 'publish_timestamp': '0', 'sharing_group_id': '0', 'disable_correlation': False, 'extends_uuid': '', 'event_creator_email': 'demo@tenzir.com', 'Org': {'id': '1', 'name': 'ORGNAME', 'uuid': '968006a7-7aab-4b3e-a272-272feac190ae', 'local': True}, 'Orgc': {'id': '1', 'name': 'ORGNAME', 'uuid': '968006a7-7aab-4b3e-a272-272feac190ae', 'local': True}, 'Attribute': [{'id': '1', 'type': 'ip-src', 'category': 'Network activity', 'to_ids': True, 'uuid': 'd4e1e06c-df1a-4171-a288-3488c6c6b115', 'event_id': '1', 'distribution': '5', 'timestamp': '1657180174', 'comment': '', 'sharing_group_id': '0', 'deleted': False, 'disable_correlation': False, 'object_id': '0', 'object_relation': None, 'first_seen': None, 'last_seen': None, 'value': '1.2.3.4', 'Galaxy': [], 'ShadowAttribute': []}], 'ShadowAttribute': [], 'RelatedEvent': [], 'Galaxy': [], 'Object': [], 'EventReport': []}
```

### Version

2.4.145

### Python version

3.9.13

### Relevant log output

```shell
This stacktrace:


DEBUG:MISP:polling 0mq socket
DEBUG:MISP:polling 0mq socket
DEBUG:MISP:polling 0mq socket
DEBUG:MISP:{'Event': {'id': '1', 'orgc_id': '1', 'org_id': '1', 'date': '2022-07-06', 'threat_level_id': '1', 'info': 'Test', 'published': False, 'uuid': '7303f304-e8f1-4318-94f3-4df43a77f0b3', 'attribute_count': '1', 'analysis': '0', 'timestamp': '1657136660', 'distribution': '1', 'proposal_email_lock': False, 'locked': False, 'publish_timestamp': '0', 'sharing_group_id': '0', 'disable_correlation': False, 'extends_uuid': '', 'event_creator_email': 'demo@tenzir.com', 'Org': {'id': '1', 'name': 'ORGNAME', 'uuid': '968006a7-7aab-4b3e-a272-272feac190ae', 'local': True}, 'Orgc': {'id': '1', 'name': 'ORGNAME', 'uuid': '968006a7-7aab-4b3e-a272-272feac190ae', 'local': True}, 'Attribute': [{'id': '1', 'type': 'ip-src', 'category': 'Network activity', 'to_ids': True, 'uuid': 'd4e1e06c-df1a-4171-a288-3488c6c6b115', 'event_id': '1', 'distribution': '5', 'timestamp': '1657136660', 'comment': '', 'sharing_group_id': '0', 'deleted': False, 'disable_correlation': False, 'object_id': '0', 'object_relation': None, 'first_seen': None, 'last_seen': None, 'value': '1.2.3.4', 'Galaxy': [], 'ShadowAttribute': []}], 'ShadowAttribute': [], 'RelatedEvent': [], 'Galaxy': [], 'Object': [], 'EventReport': []}}
Traceback (most recent call last):
  File "/Users/mavam/code/tenzir/vast-review/fabric/main.py", line 21, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mavam/code/tenzir/vast-review/fabric/main.py", line 18, in main
    await misp_task
  File "/Users/mavam/code/tenzir/vast-review/fabric/apps/misp.py", line 72, in start
    await misp.run()
  File "/Users/mavam/code/tenzir/vast-review/fabric/apps/misp.py", line 48, in run
    stix = self.stix_parser.parse_misp_event(event)
  File "/Users/mavam/code/tenzir/vast-review/fabric/env/lib/python3.9/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 81, in parse_misp_event
    self._parse_misp_event(misp_event)
  File "/Users/mavam/code/tenzir/vast-review/fabric/env/lib/python3.9/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 91, in _parse_misp_event
    self._set_identity()
  File "/Users/mavam/code/tenzir/vast-review/fabric/env/lib/python3.9/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 2415, in _set_identity
    identity = self._create_identity_object(orgc['name'])
  File "/Users/mavam/code/tenzir/vast-review/fabric/env/lib/python3.9/site-packages/misp_stix_converter/misp2stix/misp_to_stix21.py", line 1269, in _create_identity_object
    return Identity(**identity_args)
  File "/Users/mavam/code/tenzir/vast-review/fabric/env/lib/python3.9/site-packages/stix2/base.py", line 157, in __init__
    raise ExtraPropertiesError(cls, custom_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for Identity: (interoperability).
```
```


### Extra attachments

n/t

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mavam** [comment]
As a hacky way to see if it makes a difference, I tried removing all occurrences of `interoperability: True` from the STIX2 parser. Thereafter the exception vanished and calling `stix_objects` on the parser yielded the expected result:

```
[Identity(type='identity', spec_version='2.1', id='identity--968006a7-7aab-4b3e-a272-272feac190ae', created='2022-07-07T07:49:34.000Z', modified='2022-07-07T07:49:34.000Z', name='ORGNAME', identity_class='organization', revoked=False), Grouping(type='grouping', spec_version='2.1', id='grouping--7303f304-e8f1-4318-94f3-4df43a77f0b3', created_by_ref='identity--968006a7-7aab-4b3e-a272-272feac190ae', created='2022-07-07T07:49:34.000Z', modified='2022-07-07T07:49:34.000Z', name='Test', context='suspicious-activity', object_refs=['indicator--d4e1e06c-df1a-4171-a288-3488c6c6b115'], revoked=False, labels=['Threat-Report', 'misp:tool="MISP-STIX-Converter"']), Indicator(type='indicator', spec_version='2.1', id='indicator--d4e1e06c-df1a-4171-a288-3488c6c6b115', created_by_ref='identity--968006a7-7aab-4b3e-a272-272feac190ae', created='2022-07-07T07:49:34.000Z', modified='2022-07-07T07:49:34.000Z', pattern="[network-traffic:src_ref.type = 'ipv4-addr' AND network-traffic:src_ref.value = '1.2.3.4']", pattern_type='stix', pattern_version='2.1', valid_from='2022-07-07T07:49:34Z', kill_chain_phases=[KillChainPhase(kill_chain_name='misp-category', phase_name='Network activity')], revoked=False, labels=['misp:type="ip-src"', 'misp:category="Network activity"', 'misp:to_ids="True"'])]
```

Or somewhat more legible, every object in the resulting bundle pretty-printed:

```
INFO:MISP:{
    "type": "identity",
    "spec_version": "2.1",
    "id": "identity--968006a7-7aab-4b3e-a272-272feac190ae",
    "created": "2022-07-07T07:49:34.000Z",
    "modified": "2022-07-07T07:49:34.000Z",
    "name": "ORGNAME",
    "identity_class": "organization"
}
INFO:MISP:{
    "type": "grouping",
    "spec_version": "2.1",
    "id": "grouping--7303f304-e8f1-4318-94f3-4df43a77f0b3",
    "created_by_ref": "identity--968006a7-7aab-4b3e-a272-272feac190ae",
    "created": "2022-07-07T07:49:34.000Z",
    "modified": "2022-07-07T07:49:34.000Z",
    "name": "Test",
    "context": "suspicious-activity",
    "object_refs": [
        "indicator--d4e1e06c-df1a-4171-a288-3488c6c6b115"
    ],
    "labels": [
        "Threat-Report",
        "misp:tool=\"MISP-STIX-Converter\""
    ]
}
INFO:MISP:{
    "type": "indicator",
    "spec_version": "2.1",
    "id": "indicator--d4e1e06c-df1a-4171-a288-3488c6c6b115",
    "created_by_ref": "identity--968006a7-7aab-4b3e-a272-272feac190ae",
    "created": "2022-07-07T07:49:34.000Z",
    "modified": "2022-07-07T07:49:34.000Z",
    "pattern": "[network-traffic:src_ref.type = 'ipv4-addr' AND network-traffic:src_ref.value = '1.2.3.4']",
    "pattern_type": "stix",
    "pattern_version": "2.1",
    "valid_from": "2022-07-07T07:49:34Z",
    "kill_chain_phases": [
        {
            "kill_chain_name": "misp-category",
            "phase_name": "Network activity"
        }
    ],
    "labels": [
        "misp:type=\"ip-src\"",
        "misp:category=\"Network activity\"",
        "misp:to_ids=\"True\""
    ]
}
```

**Comment by mavam** [comment]
To add some context, I literally just did this and things worked. I still wonder why this fails and what is the right fix.

```diff
diff --git a/misp_stix_converter/misp2stix/misp_to_stix2.py b/misp_stix_converter/misp2stix/misp_to_stix2.py
index f59e74a..d0f69f9 100644
--- a/misp_stix_converter/misp2stix/misp_to_stix2.py
+++ b/misp_stix_converter/misp2stix/misp_to_stix2.py
@@ -153,7 +153,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
                 'misp:tool="MISP-STIX-Converter"'
             ],
             'created_by_ref': self.__identity_id,
-            'interoperability': True
         }
         markings = self._handle_event_tags_and_galaxies()
         if markings:
@@ -318,7 +317,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'labels': self._create_labels(attribute),
             'kill_chain_phases': self._create_killchain(attribute['category']),
             'created_by_ref': self.__identity_id,
-            'interoperability': True
         }
         if indicator_args is not None:
             indicator_arguments.update(indicator_args)
@@ -346,7 +344,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'number_observed': 1,
             'created_by_ref': self.__identity_id,
             'allow_custom': True,
-            'interoperability': True
         }
         observable_args.update(self._handle_observable_time_fields(attribute))
         markings = self._handle_attribute_tags_and_galaxies(
@@ -410,7 +407,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'name': attribute['value'],
             'created_by_ref': self.__identity_id,
             'labels': self._create_labels(attribute),
-            'interoperability': True,
             'created': timestamp,
             'modified': timestamp
         }
@@ -437,7 +433,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'x_misp_value': attribute['value'],
             'x_misp_type': attribute['type'],
             'x_misp_category': attribute['category'],
-            'interoperability': True
         }
         if attribute.get('comment'):
             custom_args['x_misp_comment'] = attribute['comment']
@@ -707,7 +702,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'external_references': [self._get_vulnerability_references(attribute['value'])],
             'created_by_ref': self.__identity_id,
             'labels': self._create_labels(attribute),
-            'interoperability': True,
             'created': timestamp,
             'modified': timestamp
         }
@@ -794,7 +788,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
                 'created_by_ref': self.__identity_id,
                 'created': timestamp,
                 'modified': timestamp,
-                'interoperability': True
             }
         )
         if killchain:
@@ -824,7 +817,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'created_by_ref': self.__identity_id,
             'pattern': f'[{" AND ".join(pattern)}]',
             'allow_custom': True,
-            'interoperability': True
         }
         indicator_args.update(self._handle_indicator_time_fields(misp_object))
         if misp_object.get('comment'):
@@ -853,7 +845,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'number_observed': 1,
             'created_by_ref': self.__identity_id,
             'allow_custom': True,
-            'interoperability': True
         }
         observable_args.update(self._handle_observable_time_fields(misp_object))
         markings = self._handle_object_tags_and_galaxies(
@@ -1124,7 +1115,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'x_misp_attributes': [
                 self._parse_custom_object_attribute(attribute) for attribute in misp_object['Attribute']
             ],
-            'interoperability': True
         }
         if misp_object.get('comment'):
             custom_args['x_misp_comment'] = misp_object['comment']
@@ -2314,7 +2304,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
             'name': cluster['value'],
             'description': f"{description} | {cluster['description']}",
             'labels': self._create_galaxy_labels(name, cluster),
-            'interoperability': True
         }
         if timestamp is None:
             if not cluster.get('timestamp'):
@@ -2394,7 +2383,6 @@ class MISPtoSTIX2Parser(MISPtoSTIXParser):
                 to_ids=self._fetch_ids_flag(misp_object['Attribute'])
             ),
             'created_by_ref': self.__identity_id,
-            'interoperability': True,
             'identity_class': identity_class,
         }
         markings = self._handle_object_tags_and_galaxies(
diff --git a/misp_stix_converter/misp2stix/misp_to_stix21.py b/misp_stix_converter/misp2stix/misp_to_stix21.py
index c58e9d0..e319a3d 100644
--- a/misp_stix_converter/misp2stix/misp_to_stix21.py
+++ b/misp_stix_converter/misp2stix/misp_to_stix21.py
@@ -541,7 +541,6 @@ class MISPtoSTIX21Parser(MISPtoSTIX2Parser):
                 'kill_chain_phases': self._create_killchain(misp_object['meta-category']),
                 'created_by_ref': self.identity_id,
                 'allow_custom': True,
-                'interoperability': True
             }
         )
         indicator_args.update(self._handle_indicator_time_fields(misp_object))
@@ -596,7 +595,6 @@ class MISPtoSTIX21Parser(MISPtoSTIX2Parser):
             'labels': self._create_object_labels(misp_object, to_ids=to_ids),
             'object_refs': object_refs,
             'created_by_ref': self.identity_id,
-            'interoperability': True
         }
         markings = self._handle_object_tags_and_galaxies(
             misp_object,
@@ -838,7 +836,6 @@ class MISPtoSTIX21Parser(MISPtoSTIX2Parser):
                 to_ids=self._fetch_ids_flag(misp_object['Attribute'])
             ),
             'created_by_ref': self.identity_id,
-            'interoperability': True
         }
         if misp_object.get('comment'):
             location_args['description'] = misp_object['comment']
@@ -1264,7 +1261,6 @@ class MISPtoSTIX21Parser(MISPtoSTIX2Parser):
             'modified': timestamp,
             'name': orgname,
             'identity_class': 'organization',
-            'interoperability': True
         }
         return Identity(**identity_args)
```

**Comment by adulau** [comment]
I have the impression that you are not running the latest misp-stix, could you try this `pip3 install git+https://github.com/misp/misp-stix` in the associated venv (or not) depending of your installation.

**Comment by chrisr3d** [comment]
It looks indeed like it is indeed the same situation as described here: https://github.com/MISP/MISP/issues/8459#issuecomment-1171338966.
But afair, 0mq does not use the venv that is used in MISP (within /var/www/MISP/venv by default), so updating misp-stix should be fine to make sure you have all the right versions of dependencies

**Comment by mavam** [comment]
@adulau I cloned the repo and did a `pip install .`, which should be the equivalent operation, no?

> so updating misp-stix should be fine to make sure you have all the right versions of dependencies

I just switched the latest commit (855f0f7) and I'm getting this error from the parser again:
```
ERROR:MISP:failed to parse MISP event as STIX: 'Orgc'
```

This is the corresponding input:

```
{'Event': {'id': '1', 'org_id': '1', 'date': '2022-07-11', 'info': 'Test', 'user_id': '1', 'uuid': 'dc63eeab-b15c-4c90-b59d-356180d27df1', 'published': False, 'analysis': '0', 'attribute_count': '0', 'orgc_id': '1', 'timestamp': '1657547715', 'distribution': '1', 'sharing_group_id': '0', 'proposal_email_lock': False, 'locked': False, 'threat_level_id': '1', 'publish_timestamp': '0', 'sighting_timestamp': '0', 'disable_correlation': False, 'extends_uuid': ''}, 'Orgc': {'id': '1', 'uuid': '082e1fe8-5046-4351-aa02-912ee63a9f08', 'name': 'ORGNAME'}, 'EventTag': [], 'action': 'add'}
```

FWIW: all of these runs outside of the MISP deployment, I'm having a local 0mq consumer that invokes my local version of `misp-stix`.

**Comment by adulau** [comment]
No worries, glad it works! Sometime Python can be a bit challenging for package management...
