### ISSUE TITLE
Bug: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by chandradeepcawstudios** [MISP/misp-stix#23]
### MISP-STIX usage

Python script

### Expected behavior

It should convert MISP event to Stix objects

### Actual behavior

**Case 1:** 
**event.json file content link** : https://www.circl.lu/doc/misp/feed-osint/1d87d97f-b67b-499e-b9c2-3b096c949f81.json

AtLeastOnePropertyError(
stix2.exceptions.AtLeastOnePropertyError: At least one of the (child_refs, command_line, created_time, creator_user_ref, cwd, environment_variables, granular_markings, image_ref, is_hidden, object_marking_refs, opened_connection_refs, parent_ref, pid) properties for Process must be populated.

**Case 2:**
**event.json file content link :** https://www.circl.lu/doc/misp/feed-osint/0e887f03-5aa2-4a7b-b0f7-66208c6c657b.json

TypeError: tuple indices must be integers or slices, not str

### Steps to reproduce

from misp_stix_converter import MISPtoSTIX21Parser, misp_to_stix2_1

response_21 = misp_to_stix2_1("event.json")
print(response_21)

### Version

 2.4.161

### Python version

3.8

### Relevant log output

```shell
**Case1:**

Traceback (most recent call last):
  File "test11.py", line 3744, in <module>
    response_21 = misp_to_stix2_1("event.json")
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp_stix_converter.py", line 422, in misp_to_stix2_1
    parser.parse_json_content(filename)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 59, in parse_json_content
    self.parse_misp_event(json_content)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 94, in parse_misp_event
    self._parse_misp_event(misp_event)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 104, in _parse_misp_event
    self._parse_event_data()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix21.py", line 98, in _parse_event_data
    self._handle_attributes_and_objects()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix21.py", line 120, in _handle_attributes_and_objects
    self._resolve_objects()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 781, in _resolve_objects
    getattr(self, self._mapping.objects_mapping[object_name])(misp_object)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix21.py", line 1219, in _parse_process_object
    objects.insert(0, Process(**process_args))
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/stix2/v21/base.py", line 15, in __init__
    super(_Observable, self).__init__(**kwargs)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/stix2/base.py", line 390, in __init__
    super(_Observable, self).__init__(**kwargs)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/stix2/base.py", line 241, in __init__
    self._check_object_constraints()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/stix2/v21/observables.py", line 659, in _check_object_constraints
    raise enclosing_exc
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/stix2/v21/observables.py", line 654, in _check_object_constraints
    self._check_at_least_one_property()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/stix2/base.py", line 99, in _check_at_least_one_property
    raise AtLeastOnePropertyError(
stix2.exceptions.AtLeastOnePropertyError: At least one of the (child_refs, command_line, created_time, creator_user_ref, cwd, environment_variables, granular_markings, image_ref, is_hidden, object_marking_refs, opened_connection_refs, parent_ref, pid) properties for Process must be populated.


**Case 2:**


Traceback (most recent call last):
  File "test11.py", line 3744, in <module>
    response_21 = misp_to_stix2_1("event.json")
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp_stix_converter.py", line 422, in misp_to_stix2_1
    parser.parse_json_content(filename)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 59, in parse_json_content
    self.parse_misp_event(json_content)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 94, in parse_misp_event
    self._parse_misp_event(misp_event)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 104, in _parse_misp_event
    self._parse_event_data()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix21.py", line 98, in _parse_event_data
    self._handle_attributes_and_objects()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix21.py", line 122, in _handle_attributes_and_objects
    self._resolve_objects_to_parse()
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 1976, in _resolve_objects_to_parse
    self._parse_custom_object(misp_object)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 1153, in _parse_custom_object
    custom_id = getattr(self, self._id_parsing_function['object'])('x-misp-object', misp_object)
  File "/home/chandra/test/PythonTestCode/venv/lib/python3.8/site-packages/misp_stix_converter/misp2stix/misp_to_stix2.py", line 109, in _define_stix_object_id
    return f"{feature}--{misp_object['uuid']}"
TypeError: tuple indices must be integers or slices, not str
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
Some cases were basically STIX required fields that were missing because the MISP objects don't contain the equivalent attributes, which is not an issue we can fix. Nonetheless we were missing some exceptions catching to redirect the execution of the code to the creation of custom objects when there are missing required STIX fields.
With those exceptions better caught, there should not be anymore `AtLeastOnePropertyError` exceptions raised like in your 1st case

I also fixed other issues (like the one you faced with your case 2) I discovered while testing every sample available in the OSINT feed.

I will have a closer look at the warnings and errors that are caught to make sure I did not miss issues that are not related to missing STIX fields. For now it should be working, but let me know if you face any further issue or get any suspicious error message
