### ISSUE TITLE
Bug: stix2.exceptions.InvalidValueError: Invalid value for Sighting 'sighting_of_ref': reference to custom object type: x-misp-attribute

### ISSUE THREAD

**Issue by cudeso** [MISP/misp-stix#49]
### MISP-STIX usage

Standalone

### Expected behavior

Parsing of an event with a sighting. Almost all events with sightings are properly parsed, except one event.

### Actual behavior

When parsing the event with UUID (5f46b4ae-a1a9-4e3e-ba99-9ead115a74ab - it's on MISPPRIV) these errors are raised:

```
  File "/home/koenv/misp2sentinel/sentinel/lib/python3.8/site-packages/stix2/base.py", line 59, in _check_property
    raise InvalidValueError(
stix2.exceptions.InvalidValueError: Invalid value for Sighting 'sighting_of_ref': reference to custom object type: x-misp-attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/koenv/misp2sentinel/sentinel/lib/python3.8/site-packages/stix2/base.py", line 53, in _check_property
    kwargs[prop_name], has_custom = prop.clean(*arguments)
  File "/home/koenv/misp2sentinel/sentinel/lib/python3.8/site-packages/stix2/properties.py", line 616, in clean
    raise CustomContentError(
stix2.exceptions.CustomContentError: reference to custom object type: x-misp-attribute


  File "/home/koenv/misp2sentinel/sentinel/lib/python3.8/site-packages/stix2/base.py", line 59, in _check_property
    raise InvalidValueError(
stix2.exceptions.InvalidValueError: Invalid value for Sighting 'sighting_of_ref': reference to custom object type: x-misp-attribute
```

### Steps to reproduce

Parse the event with UUID `5f46b4ae-a1a9-4e3e-ba99-9ead115a74ab` with

```
parser = MISPtoSTIX21Parser()
parser.parse_misp_event(event)
```

### Version

2.4.171

### Python version

3.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrisr3d** [comment]
There was indeed a missing `allow_custom` flag when the reference of a sighting in a custom object
Thanks
